config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'confirm_user', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'ban_user', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]
  resources :styles, only:[:index, :show]

  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'
  get 'brewerylist', to: 'breweries#list'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage
  validates :username, uniqueness: true,
                       length: {within: 3..15}
  validates :password,  length: {minimum: 4}
  validate :at_least_one_upper
  validate :at_least_one_number

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings

  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships


  has_secure_password

  def at_least_one_upper
    if not /[A-Z]/.match(password)
      errors.add(:password, "must contain at least one upper character")
    end
  end

  def at_least_one_number
    if not /[0-9]/.match(password)
      errors.add(:password, "must contain at least one number")
    end
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?
    group = ratings.group_by {|r| r.beer.style.name}
    averages = group.map { |k, v| v.inject(0.0){ |sum, i| sum + i.score} / v.size}
    Hash[group.keys.zip(averages)].max.first
  end

  def favorite_brewery
    Hash[ratings.group_by {|r| r.beer.brewery.name}.keys.zip(ratings.group_by {|r| r.beer.brewery.name}.map { |k, v| v.inject(0.0){ |sum, i| sum + i.score} / v.size})].max.first rescue nil
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |b| -(b.ratings.count||0) }
    sorted_by_rating_in_desc_order[0..n]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      session.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def ban_user
    user = User.find(params[:id])
    user.update_attribute :banned, (not user.banned)
    new_status = user.banned? ? "banned" : "unbanned"

    redirect_to :back, notice:"user has been #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td><%= link_to 'Show', user, class:'btn btn-info' %></td>
        <td><% if user.banned %> BANNEDED <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @user.username %></strong>
</p>

<% if @user.banned %>
  <h1> BANNEDED!!!111 </h1>
<% end %>

<p>Has made <%= pluralize(@user.ratings.count, "rating") %> average <%= @user.average_rating %></p>
<p>Favorite beer style <%= @user.favorite_style%></p>
<p>Favorite brewery <%= @user.favorite_brewery%></p>

Member of
<% @user.memberships.each do |membership| %>
    <% if @user == current_user %>
       <%= link_to membership.beer_club.to_s, membership.beer_club %>
    <% end %>
<% end %>

<ul>
 <% @user.ratings.each do |rating| %>
   <li>
     <%= rating %>
     <% if @user == current_user %>
        <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
     <% end %>
    </li>
 <% end %>
</ul>

<% if current_user and current_user.admin %>
  <%= link_to "BAN USER", ban_user_user_path(@user.id), method: :post, class: "btn btn-danger" %>
<% end %>


<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', users_path %>